### ISSUE TITLE
Report doesn't update on changes

### ISSUE THREAD

**Issue by StarfallProjects** [Rebilly/lexi#178]
Hi! I love this project, thank you for creating and open sourcing it.

I've installed the Lexi GitHub Action and it's working great. However, if you make changes to a pull request after opening it, although the action runs again, the report doesn't update, and there's no new report added.
I'm fairly new to using GitHub Actions, so maybe I just need to configure something there, but I'm unsure. Is there a way to update the displayed report every time the action runs? And is this something I should be doing in the config, or you need to be doing in the action itself?

**Comment by noon-dawg** [comment]
Hi @StarfallProjects!

The scores displayed in the GitHub action represent the metrics from the most recent commit.

Lexi displays a report for each commit. I see now that we may need to document this, because it is a little bit hidden.

To view metrics on changes after each commit in a pull request: At the top right of the GitHub action, click **edited**, then select the commit report that you want to view.

<img src="https://github.com/Rebilly/lexi/assets/85164331/953d0515-2421-47b0-b50a-e7169bc7695f" width="60%">

#### Example of previous commit

<img src="https://github.com/Rebilly/lexi/assets/85164331/576ec601-d791-4e19-aa87-01acd9d90d76" width="60%">

**Comment by StarfallProjects** [comment]
Thank you!

**Comment by noon-dawg** [comment]
We've added docs for this to the [readme](https://github.com/Rebilly/lexi?tab=readme-ov-file#view-reports-from-previous-commits).

Thanks for reaching out and for the feedback @StarfallProjects!
