### ISSUE TITLE
Option to not upsert comment on GitHub Action

### ISSUE THREAD

**Issue by npentrel** [Rebilly/lexi#80]
Hi folks!

My team has now been using Lexi since Write the Docs and one thing I didn't fully realize till today is that the comment with the readability scores upserts. I think it would actually be useful to have the option to configure that. Consider the following use case:

1. Writer A submits a PR - lexi says readability score 50.
2. Writer B submits feedback on the PR.
3. Writer A adds new commits implementing that feedback - lexi says readability score is now 55. 

In the current setup I don't see the old score anymore. So unless I remember the score, I won't know whether things have improved or whether the feedback actually made things worse.

This could be spammy on the PR, amending the table to add extra columns (with readability scores at each commit as they change compared to the beginning of the PR) would probably be cleaner but also a bit more complex. Something like this:

File | Readability (7782d27) | Readability (a1c3858) | Readability (c94bdca)
-- | -- | -- | -- 
connectivity.md | 24.18 (🔴 -21.88) | 24.18 (🔴 -21.88) | 24.18 (🔴 -21.88)
python-venv.md | 69.03 (🔴 -0.76) | 68.00 (🔴 -1.79) | -

Overall readability score: 55.07 (🔴 -0.07)

If you agree this would be a useful addition to lexi, I'm happy to have a go at adding the no-upsert functionality - but also happy for you to do it. The table idea, while I think better, probably requires more understanding of the tool you've built than I have time to acquire right now (but maybe in the future) - again, if you agree that's useful, of course.

Cheers,
Naomi

**Comment by Weetbix** [comment]
Hey Naomi!

We love to hear that you have been using Lexi :)

Did you know that you can see the history of the comment in the `edited` dropdown?
<img width="592" alt="image" src="https://github.com/Rebilly/lexi/assets/492636/9782af10-27ee-4b69-a486-fbde6c944cc9">
<img width="661" alt="image" src="https://github.com/Rebilly/lexi/assets/492636/b2b7789b-d627-4f96-9f79-b642efc99fa8">

Do you think that suffices for your use case?

The advantage of that is that you can see the diff in scores, but the disadvantage is that its more difficult to attribute the changes to a particular commit, as the edits are listed by date.

If you think no-upsert has better dx we can certainly go ahead with that idea! If you would like to contribute it it would definitely be welcome, otherwise we could get to it in a couple of weeks.

I think the table idea would get unwieldy with longer lasting PRs and more commits

**Comment by npentrel** [comment]
🤯 brilliant! That does exactly what I want and no code changes needed. Thank you for the quick and thorough reply!
